name: grocerydelivery
description: A new Flutter application
version: 2.2.1+30

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.18.0
  getwidget: ^1.1.0
  http: ^0.12.0+4
  google_maps_flutter: ^0.5.25+3
  flutter_polyline_points: ^0.1.0
  location: ^3.0.2
  solid_bottom_sheet: ^0.1.9
  shared_preferences: ^0.5.6+3
  socket_io_client: ^0.9.9
  provider: ^4.0.4
  url_launcher: ^5.4.10
  intl: ^0.16.1
  onesignal_flutter: ^2.4.1
  flutter_i18n: ^0.13.0
  flutter_dotenv: ^2.1.0
  pin_entry_text_field: ^0.1.3
  pull_to_refresh: ^1.5.7
  http_interceptor: ^0.3.2
  fluttertoast: ^7.0.1
  image_picker: ^0.6.3+1
  connectivity: ^0.4.9+5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.5"

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/icons/history.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/profile.svg
    - lib/assets/logo.png
    - lib/assets/icons/logo_outline.png
    - lib/assets/icons/back_arrow.png
    - lib/assets/icons/hash.svg
    - lib/assets/icons/location.svg
    - lib/assets/icons/customer.svg
    - lib/assets/icons/phone.png
    - lib/assets/icons/locate.png
    - lib/assets/icons/homepin.png
    - lib/assets/icons/agentpin.png
    - lib/assets/icons/storepin.png
    - lib/assets/icons/timer.png
    - lib/assets/splash.png
    
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: lib/assets/fonts/poppinsBold.ttf
          weight: 400

    - family: PoppinsRegular
      fonts:
        - asset: lib/assets/fonts/poppinsRegular.ttf
          weight: 400

    - family: PoppinsMedium
      fonts:
        - asset: lib/assets/fonts/poppinsMedium.ttf
          weight: 400

    - family: PoppinsSemiBold
      fonts:
        - asset: lib/assets/fonts/poppinsSemiBold.ttf
          weight: 400

    - family: SFProTextSemiBold
      fonts:
        - asset: lib/assets/fonts/SFProTextSemibold.ttf
          weight: 400
