name: grocerydelivery
description: A new Flutter application
version: 3.0.4+35
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  getwidget: ^2.0.5 
  http: ^0.13.4
  google_maps_flutter: ^2.1.3
  flutter_polyline_points: ^1.0.0
  geolocator: ^8.2.0
  solid_bottom_sheet: ^0.1.10
  shared_preferences: ^2.0.13
  socket_io_client: ^1.0.2
  provider: ^6.0.2
  url_launcher: ^6.0.20
  intl: ^0.17.0
  onesignal_flutter: ^3.3.0
  flutter_i18n: ^0.32.1
  flutter_config: ^2.0.0
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  http_interceptor: ^1.0.2
  fluttertoast: ^8.0.9
  image_picker: ^0.8.4+11
  connectivity: ^3.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/icons/history.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/profile.svg
    - lib/assets/logo.png
    - lib/assets/icons/logo_outline.png
    - lib/assets/icons/back_arrow.png
    - lib/assets/icons/hash.svg
    - lib/assets/icons/location.svg
    - lib/assets/icons/customer.svg
    - lib/assets/icons/phone.png
    - lib/assets/icons/locate.png
    - lib/assets/icons/homepin.png
    - lib/assets/icons/agentpin.png
    - lib/assets/icons/storepin.png
    - lib/assets/icons/timer.png
    - lib/assets/splash.png
    
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: lib/assets/fonts/poppinsBold.ttf
          weight: 400

    - family: PoppinsRegular
      fonts:
        - asset: lib/assets/fonts/poppinsRegular.ttf
          weight: 400

    - family: PoppinsMedium
      fonts:
        - asset: lib/assets/fonts/poppinsMedium.ttf
          weight: 400

    - family: PoppinsSemiBold
      fonts:
        - asset: lib/assets/fonts/poppinsSemiBold.ttf
          weight: 400

    - family: SFProTextSemiBold
      fonts:
        - asset: lib/assets/fonts/SFProTextSemibold.ttf
          weight: 400
