name: grocerydelivery
description: A new Flutter application
version: 4.0.0+40
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_svg: ^0.22.0
  getwidget: 
    git:
      url: https://github.com/ionicfirebaseapp/getwidget.git
  http: ^0.13.3
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  location: ^4.3.0
  solid_bottom_sheet: ^0.1.10
  shared_preferences: ^2.0.6
  socket_io_client: ^1.0.1
  provider: ^5.0.0
  url_launcher: ^6.0.9
  intl: ^0.17.0
  onesignal_flutter: ^3.0.0
  flutter_i18n: ^0.22.4
  flutter_dotenv: ^5.0.0
  pin_code_fields: ^7.2.0
  pull_to_refresh: ^2.0.0
  http_interceptor: ^1.0.0
  fluttertoast: ^8.0.7
  image_picker: ^0.8.1+3
  connectivity: ^3.0.6
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/icons/history.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/profile.svg
    - lib/assets/logo.png
    - lib/assets/icons/logo_outline.png
    - lib/assets/icons/back_arrow.png
    - lib/assets/icons/hash.svg
    - lib/assets/icons/location.svg
    - lib/assets/icons/customer.svg
    - lib/assets/icons/phone.png
    - lib/assets/icons/locate.png
    - lib/assets/icons/homepin.png
    - lib/assets/icons/agentpin.png
    - lib/assets/icons/storepin.png
    - lib/assets/icons/timer.png
    - lib/assets/splash.png
    
  fonts:
    - family: PoppinsBold
      fonts:
        - asset: lib/assets/fonts/poppinsBold.ttf
          weight: 400

    - family: PoppinsRegular
      fonts:
        - asset: lib/assets/fonts/poppinsRegular.ttf
          weight: 400

    - family: PoppinsMedium
      fonts:
        - asset: lib/assets/fonts/poppinsMedium.ttf
          weight: 400

    - family: PoppinsSemiBold
      fonts:
        - asset: lib/assets/fonts/poppinsSemiBold.ttf
          weight: 400

    - family: SFProTextSemiBold
      fonts:
        - asset: lib/assets/fonts/SFProTextSemibold.ttf
          weight: 400
