class JsonData {
  static String englishJsonCode = "en";
  static Map englishJson = {
    englishJsonCode: {
      "NO_INTERNET": "No Internet connection",
      "NO_INTERNET_MSG":
          "requires an internet connection. Check your connection then try again.",
      "ONLINE_MSG": "Now you are online.",
      "ORDER_FROM": "Order From",
      "SUCCESS": "Success",
      "FAILED": "Failed",
      "WALLET": "Wallet",
      "ACCEPT": "Accept",
      "ACCEPT_TRACK": "Accept & Track",
      "ACCEPTED_REQUESTS_LIST": "Accepted Requests List",
      "ACCPETED": "Accepted",
      "ACTIVE_REQUESTS": "Active Requests",
      "ADDRESS": "Address",
      "AUTHORICATION_ERROR": "is not authorised to lOGIN to Delivery App.",
      "CASH_ON_DELIVERY": "Cash on Delivery",
      "CHANGE_PASSWORD": "Change Password",
      "CHOOSE_FROM_PHOTOS": "Choose From Photos",
      "CLOSE": "Close",
      "CODE_MSG": "We have sent a 4 digits code to",
      "COMPLETED_REQUESTS": "Completed requests",
      "CONFIRM": "Confirm",
      "CONTACT_NUMBER": "Contact Number",
      "CUSTOMER": "Customer",
      "DATE": "Date",
      "DATE_TIME": "Date/time",
      "DELIVERD": "Deliverd",
      "DELIVERY_CHARGES": "Delivery Charges",
      "DELIVERY_TYPE": "Delivery Type",
      "DIRECTIONS": "Directions",
      "DISCOUNT": "Discount",
      "DO_NOT_ENTER_SAME_PASS":
          "Do not enter same old password and new password",
      "EDIT_PROFILE": "Edit Profile",
      "EMAIL": "Email",
      "EMAIL_ID": "Email Id",
      "ENTER_CONFIRM_PASSWORD": "Enter Confirm Password",
      "ENTER_FIRST_NAME": "Enter First Name",
      "ENTER_LAST_NAME": "Enter Last Name",
      "ENTER_NEW_PASSWORD": "Enter New Password",
      "ENTER_OLD_PASSWORD": "Enter Old Password",
      "ENTER_PASSWORD": "Enter Password",
      "ENTER_VERIFICATION_CODE": "Enter Verification Code",
      "ENTER_YOUR_CONTACT_NUMBER": "Enter Your Contact Number",
      "ENTER_YOUR_EMAIL": "Enter Your Email",
      "ERROR": "Error",
      "ERROR_EMAIL": "Please enter a valid email",
      "ERROR_MAIL": "Please Enter Valid Email",
      "ERROR_PASS": "Please Enter Min 6 Digit Password",
      "ERROR_PASSWORD": "Password should be atleast 6 char long",
      "FIRST_NAME": "First Name",
      "FORET_PASS_MESSAGE":
          "Please enter your registered Email to send the reset code",
      "FORGET_PASSWORD": "Forget Password",
      "HISTORY": "History",
      "HOME": "Home",
      "ID": "Id",
      "ITEMS": "Items",
      "LAST_NAME": "Last Name",
      "LOGIN": "Login",
      "LOGOUT": "Logout",
      "LOGOUT_SUCCESSFULL": "Logout Successfull",
      "MANAGER": "Manger",
      "MOBILE_NUMBER": "Mobile Number",
      "NO_ACTIVE_REQUESTS": "No active requests found!",
      "NO_DELIVERED_ORDERS": "No delivered orders found!",
      "NO_REQUESTS_LIST": "Np Requests List Found!",
      "OK": "Ok",
      "ORDER_COMPLETED": "Order Completed",
      "ORDER_DELIVERED": "Order Delivered",
      "ORDER_DETAILS": "Order Details",
      "ORDER_ID": "Order Id",
      "ORDERS": "Orders",
      "OTP_MSG": "Please Enter 4 Digits OTP",
      "PASS_NOT_MATCH": "Passwords do not match",
      "PASSWORD": "Password",
      "PASSWORD_RESET": "Password Reset",
      "PAYBYCARD": "Pay By Card",
      "PAYMENT": "Payment",
      "PAYMENT_STATUS": "Payment Status",
      "PENDING": "Pending",
      "PROFILE": "Profile",
      "RE_ENTER_NEW_PASSWORD": "Re Enter New Password",
      "REJECT": "Reject",
      "REMOVE_PHOTO": "Remove Photo",
      "REQUEST_ID": "Request Id",
      "RESENT_OTP": "Resent OTP",
      "RESET": "Reset",
      "SELECT": "Select",
      "SELECT_LANGUAGE": "Select Language",
      "START": "Start",
      "STARTED": "Started",
      "STORE": "Store",
      "SUB_TOTAL": "Sub Total",
      "SUBMIT": "Submit",
      "TAKE_PHOTO": "Take Photo",
      "TAX": "Tax",
      "TIME": "Time",
      "TO_CUSTOMER": "To Customer",
      "TO_STORE": "To Store",
      "TOTAL": "Total",
      "TRACK": "Track",
      "USER_NAME": "User Name",
      "VEHICLE_TYPE": "Vehicle Type",
      "VERIFY_OTP": "Verify OTP",
      "WELCOME": "Welcome",
      "WRONG_FORMAT":
          "Something went wrong!, Received Data was in wrong format!",
      "YOU_HAVE_UPDATED_STATUS_TO_OUT_FOR_DELIVERY":
          "You have updated status to out for delivery"
    }
  };
}
